export type Stage = {
  name: string;
  /** Fraction of the season (0-1) at which this stage begins. */
  startFrac: number;
  desc: string;
  critical: boolean;
  /** FAO-56 style crop coefficient for this stage. */
  kc: number;
};

export type Crop = {
  key: string;
  label: string;
  icon: string;
  family: "Cereal" | "Oilseed" | "Legume" | "Fibre" | "Root & Tuber" | "Vegetable" | "Sugar";
  /** Typical season length in days, planting -> harvest. */
  seasonDays: number;
  /** Typical accumulated growing degree days over a full season. */
  gddTotal: number;
  gddBase: number;
  gddCap: number;
  /** Total available water in the root zone, mm. Drives the depletion model. */
  taw: number;
  /** Depletion fraction that triggers irrigation advice (FAO-56 "p"). */
  depletionTrigger: number;
  stages: Stage[];
  frostSensitiveStages: string[];
  frostThreshold: number;
  heatSensitiveStages: string[];
  heatThreshold: number;
  /** Flooded / paddy crops are not managed on a rainfed depletion model. */
  flooded?: boolean;
  pests: string[];
  diseases: string[];
  tips: string[];
  caveat: string;
};

export const CROPS: Crop[] = [
  {
    key: "corn",
    label: "Corn (Maize)",
    icon: "🌽",
    family: "Cereal",
    seasonDays: 140,
    gddTotal: 1400,
    gddBase: 10,
    gddCap: 30,
    taw: 110,
    depletionTrigger: 0.5,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings break through the soil and the root system starts.", critical: false, kc: 0.3 },
      { name: "Vegetative Growth", startFrac: 0.08, desc: "Leaves develop and the plant builds its structure.", critical: false, kc: 0.7 },
      { name: "Tasseling & Silking", startFrac: 0.26, desc: "Flowering — the single most water-sensitive stage of the season.", critical: true, kc: 1.2 },
      { name: "Grain Filling", startFrac: 0.47, desc: "Kernels develop and fill out. Still highly water-sensitive.", critical: true, kc: 1.05 },
      { name: "Maturity", startFrac: 0.72, desc: "Grain dries down and the crop approaches harvest.", critical: false, kc: 0.6 },
    ],
    frostSensitiveStages: ["Emergence", "Vegetative Growth"],
    frostThreshold: 2,
    heatSensitiveStages: ["Tasseling & Silking"],
    heatThreshold: 35,
    pests: ["Corn earworm", "European corn borer", "Fall armyworm", "Rootworm larvae"],
    diseases: ["Gray leaf spot", "Northern corn leaf blight", "Common rust"],
    tips: [
      "Rotate with a non-host crop (e.g. soybean) to break pest and disease cycles.",
      "Scout weekly through tasseling for earworm and armyworm activity.",
      "Avoid nitrogen shortfall going into grain filling — it worsens drought stress.",
    ],
    caveat: "Models a typical full-season grain corn cycle. Hybrid maturity ratings (90-day vs 115-day) shift exact timing.",
  },
  {
    key: "wheat_spring",
    label: "Spring Wheat",
    icon: "🌾",
    family: "Cereal",
    seasonDays: 120,
    gddTotal: 1700,
    gddBase: 0,
    gddCap: 30,
    taw: 100,
    depletionTrigger: 0.55,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings emerge and establish.", critical: false, kc: 0.3 },
      { name: "Tillering", startFrac: 0.09, desc: "The plant produces side shoots from its base — this sets head count.", critical: false, kc: 0.5 },
      { name: "Stem Extension", startFrac: 0.26, desc: "Stems elongate rapidly (jointing) as the plant builds height.", critical: false, kc: 0.85 },
      { name: "Heading & Flowering", startFrac: 0.47, desc: "Heads emerge and flower — sensitive to both frost and heat.", critical: true, kc: 1.15 },
      { name: "Grain Filling", startFrac: 0.63, desc: "Kernels fill. Water and heat sensitive.", critical: true, kc: 0.95 },
      { name: "Ripening", startFrac: 0.84, desc: "The crop dries down toward harvest.", critical: false, kc: 0.35 },
    ],
    frostSensitiveStages: ["Heading & Flowering"],
    frostThreshold: 0,
    heatSensitiveStages: ["Heading & Flowering", "Grain Filling"],
    heatThreshold: 32,
    pests: ["Aphids", "Hessian fly", "Wheat stem sawfly"],
    diseases: ["Leaf & stripe rust", "Powdery mildew", "Fusarium head blight"],
    tips: [
      "Watch for rust from stem extension through heading — it spreads fast in humid weather.",
      "Avoid excess late nitrogen: it raises disease pressure and lodging risk.",
      "Fusarium head blight risk climbs sharply with wet weather during flowering.",
    ],
    caveat: "Spring wheat: sown in spring, no winter dormancy. If you sowed in autumn, use Winter Wheat instead.",
  },
  {
    key: "wheat_winter",
    label: "Winter Wheat",
    icon: "❄️",
    family: "Cereal",
    seasonDays: 250,
    gddTotal: 2100,
    gddBase: 0,
    gddCap: 30,
    taw: 110,
    depletionTrigger: 0.55,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Autumn sowing emerges and establishes before the cold.", critical: false, kc: 0.3 },
      { name: "Autumn Tillering", startFrac: 0.06, desc: "The plant tillers and builds roots ahead of winter.", critical: false, kc: 0.45 },
      { name: "Winter Dormancy", startFrac: 0.18, desc: "Growth pauses through the cold months. Very little water is used.", critical: false, kc: 0.35 },
      { name: "Spring Green-Up", startFrac: 0.5, desc: "Growth restarts and remaining tillers develop.", critical: false, kc: 0.6 },
      { name: "Stem Extension", startFrac: 0.62, desc: "Rapid jointing and height growth.", critical: false, kc: 0.9 },
      { name: "Heading & Flowering", startFrac: 0.76, desc: "Heads emerge and flower — the yield-defining window.", critical: true, kc: 1.15 },
      { name: "Grain Filling", startFrac: 0.86, desc: "Kernels fill. Heat and drought here cut yield directly.", critical: true, kc: 0.95 },
      { name: "Ripening", startFrac: 0.95, desc: "Dry-down toward harvest.", critical: false, kc: 0.35 },
    ],
    frostSensitiveStages: ["Heading & Flowering"],
    frostThreshold: 0,
    heatSensitiveStages: ["Heading & Flowering", "Grain Filling"],
    heatThreshold: 32,
    pests: ["Aphids (virus vectors)", "Slugs at establishment", "Wireworm"],
    diseases: ["Septoria leaf blotch", "Yellow & brown rust", "Fusarium head blight", "Take-all"],
    tips: [
      "Dormancy timing shifts a lot with latitude — treat the winter window as indicative only.",
      "Septoria is the main driver of fungicide timing in wet maritime climates.",
      "Water balance during dormancy is not meaningful; watch it again from green-up.",
    ],
    caveat: "Winter wheat spans roughly 8 months including a dormant period whose length depends heavily on your climate.",
  },
  {
    key: "barley",
    label: "Barley",
    icon: "🌾",
    family: "Cereal",
    seasonDays: 110,
    gddTotal: 1500,
    gddBase: 0,
    gddCap: 30,
    taw: 95,
    depletionTrigger: 0.55,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings emerge.", critical: false, kc: 0.3 },
      { name: "Tillering", startFrac: 0.09, desc: "Side shoots form from the base.", critical: false, kc: 0.5 },
      { name: "Stem Extension", startFrac: 0.27, desc: "Rapid jointing and height growth.", critical: false, kc: 0.85 },
      { name: "Heading & Flowering", startFrac: 0.48, desc: "Heads emerge and flower.", critical: true, kc: 1.15 },
      { name: "Grain Filling", startFrac: 0.64, desc: "Grain fills — key window for malting quality.", critical: true, kc: 0.9 },
      { name: "Ripening", startFrac: 0.85, desc: "Dry-down toward harvest.", critical: false, kc: 0.3 },
    ],
    frostSensitiveStages: ["Heading & Flowering"],
    frostThreshold: 0,
    heatSensitiveStages: ["Grain Filling"],
    heatThreshold: 30,
    pests: ["Aphids", "Cereal leaf beetle"],
    diseases: ["Net blotch", "Powdery mildew", "Ramularia", "Scald"],
    tips: [
      "Barley is more drought-tolerant than wheat but less tolerant of waterlogging.",
      "For malting barley, protein is pushed up by late nitrogen and by heat during grain fill.",
      "Net blotch carries over in stubble — rotation matters.",
    ],
    caveat: "Modelled as spring barley. Winter barley sown in autumn runs a longer cycle with a dormant period.",
  },
  {
    key: "rice",
    label: "Rice (Paddy)",
    icon: "🍚",
    family: "Cereal",
    seasonDays: 150,
    gddTotal: 2000,
    gddBase: 10,
    gddCap: 35,
    taw: 60,
    depletionTrigger: 0.2,
    flooded: true,
    stages: [
      { name: "Establishment", startFrac: 0, desc: "Transplanting or direct seeding, with the field kept saturated.", critical: false, kc: 1.05 },
      { name: "Tillering", startFrac: 0.13, desc: "Tillers multiply — the field is normally kept shallow-flooded.", critical: false, kc: 1.1 },
      { name: "Panicle Initiation", startFrac: 0.4, desc: "Panicles form inside the stem. Never let the field dry out here.", critical: true, kc: 1.2 },
      { name: "Flowering", startFrac: 0.57, desc: "Anthesis — extremely sensitive to heat and to any water shortage.", critical: true, kc: 1.2 },
      { name: "Grain Filling", startFrac: 0.7, desc: "Grains fill and ripen.", critical: true, kc: 1.05 },
      { name: "Maturity", startFrac: 0.87, desc: "Field is drained before harvest.", critical: false, kc: 0.75 },
    ],
    frostSensitiveStages: ["Establishment", "Tillering", "Panicle Initiation", "Flowering"],
    frostThreshold: 5,
    heatSensitiveStages: ["Flowering"],
    heatThreshold: 35,
    pests: ["Stem borer", "Brown planthopper", "Rice leaffolder"],
    diseases: ["Rice blast", "Bacterial leaf blight", "Sheath blight"],
    tips: [
      "Rainfall alone rarely covers paddy demand — this tool shows the shortfall your irrigation must cover.",
      "Night temperatures above roughly 24°C during flowering cause sterile grains.",
      "Alternate wetting and drying can save water, but not during panicle initiation or flowering.",
    ],
    caveat: "Assumes continuously flooded lowland paddy. Upland and aerobic rice use far less water and run different timings.",
  },
  {
    key: "sorghum",
    label: "Sorghum",
    icon: "🌾",
    family: "Cereal",
    seasonDays: 125,
    gddTotal: 1400,
    gddBase: 10,
    gddCap: 34,
    taw: 120,
    depletionTrigger: 0.55,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings emerge.", critical: false, kc: 0.3 },
      { name: "Vegetative Growth", startFrac: 0.09, desc: "Leaves and stalk develop.", critical: false, kc: 0.7 },
      { name: "Booting & Flowering", startFrac: 0.42, desc: "The head emerges and flowers — the critical yield window.", critical: true, kc: 1.05 },
      { name: "Grain Filling", startFrac: 0.6, desc: "Grain fills out.", critical: true, kc: 0.95 },
      { name: "Maturity", startFrac: 0.82, desc: "Grain hardens toward harvest.", critical: false, kc: 0.55 },
    ],
    frostSensitiveStages: ["Emergence", "Vegetative Growth"],
    frostThreshold: 2,
    heatSensitiveStages: ["Booting & Flowering"],
    heatThreshold: 38,
    pests: ["Sorghum midge", "Shoot fly", "Aphids"],
    diseases: ["Anthracnose", "Grain mould", "Downy mildew"],
    tips: [
      "Sorghum recovers from drought better than corn — don't panic at a short dry spell in vegetative growth.",
      "Grain mould risk rises when it stays wet through grain fill.",
      "Bird damage near maturity can be a bigger loss than any disease.",
    ],
    caveat: "Grain sorghum timings vary widely by hybrid and by photoperiod sensitivity.",
  },
  {
    key: "soybean",
    label: "Soybean",
    icon: "🫘",
    family: "Legume",
    seasonDays: 130,
    gddTotal: 1300,
    gddBase: 10,
    gddCap: 30,
    taw: 110,
    depletionTrigger: 0.5,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings emerge and the first leaves open.", critical: false, kc: 0.35 },
      { name: "Vegetative Growth", startFrac: 0.08, desc: "Nodes and leaves develop; nodules start fixing nitrogen.", critical: false, kc: 0.7 },
      { name: "Flowering", startFrac: 0.35, desc: "Flowers set at the nodes.", critical: true, kc: 1.1 },
      { name: "Pod Development", startFrac: 0.5, desc: "Pods form — shedding happens fast under stress.", critical: true, kc: 1.15 },
      { name: "Seed Filling", startFrac: 0.65, desc: "Seeds fill. This is the highest-value water window of the season.", critical: true, kc: 1.05 },
      { name: "Maturity", startFrac: 0.85, desc: "Leaves yellow and drop; pods dry down.", critical: false, kc: 0.5 },
    ],
    frostSensitiveStages: ["Emergence", "Vegetative Growth", "Seed Filling", "Maturity"],
    frostThreshold: 1,
    heatSensitiveStages: ["Flowering", "Pod Development"],
    heatThreshold: 35,
    pests: ["Soybean aphid", "Bean leaf beetle", "Stink bugs", "Spider mites"],
    diseases: ["Sudden death syndrome", "White mould (sclerotinia)", "Soybean rust", "Frogeye leaf spot"],
    tips: [
      "Seed fill is where irrigation pays back most — protect it before earlier stages.",
      "White mould risk rises with a dense canopy and cool wet flowering weather.",
      "Soybean fixes its own nitrogen; extra N fertiliser usually just costs money.",
    ],
    caveat: "Maturity group strongly changes season length — a group 0 crop in the north is far shorter than a group 5 in the south.",
  },
  {
    key: "chickpea",
    label: "Chickpea",
    icon: "🫛",
    family: "Legume",
    seasonDays: 115,
    gddTotal: 1300,
    gddBase: 5,
    gddCap: 30,
    taw: 100,
    depletionTrigger: 0.55,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings emerge.", critical: false, kc: 0.4 },
      { name: "Vegetative Growth", startFrac: 0.1, desc: "Branches and canopy develop.", critical: false, kc: 0.7 },
      { name: "Flowering", startFrac: 0.42, desc: "Flowering begins — sensitive to both heat and waterlogging.", critical: true, kc: 1.0 },
      { name: "Pod Filling", startFrac: 0.6, desc: "Pods fill out.", critical: true, kc: 0.95 },
      { name: "Maturity", startFrac: 0.83, desc: "The crop dries down for harvest.", critical: false, kc: 0.35 },
    ],
    frostSensitiveStages: ["Flowering", "Pod Filling"],
    frostThreshold: 0,
    heatSensitiveStages: ["Flowering", "Pod Filling"],
    heatThreshold: 32,
    pests: ["Pod borer (Helicoverpa)", "Aphids", "Cutworm"],
    diseases: ["Ascochyta blight", "Fusarium wilt", "Botrytis grey mould"],
    tips: [
      "Chickpea hates wet feet — waterlogging does more damage than a dry spell.",
      "Ascochyta blight explodes after rain during flowering; scout right after wet spells.",
      "Heat above ~32°C at flowering causes flower drop and empty pods.",
    ],
    caveat: "Desi and Kabuli types differ in season length and disease tolerance. Timings shown are indicative.",
  },
  {
    key: "cotton",
    label: "Cotton",
    icon: "☁️",
    family: "Fibre",
    seasonDays: 160,
    gddTotal: 1500,
    gddBase: 15.5,
    gddCap: 32,
    taw: 130,
    depletionTrigger: 0.55,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings emerge from the soil.", critical: false, kc: 0.35 },
      { name: "Squaring", startFrac: 0.07, desc: "Floral buds (squares) form while the plant builds structure.", critical: false, kc: 0.7 },
      { name: "Flowering (Bloom)", startFrac: 0.29, desc: "Flowers open and pollinate — the most water- and heat-sensitive stage.", critical: true, kc: 1.15 },
      { name: "Boll Development", startFrac: 0.47, desc: "Bolls form and fill with fibre. Still highly water-sensitive.", critical: true, kc: 1.05 },
      { name: "Boll Opening", startFrac: 0.72, desc: "Bolls open and the crop dries down toward picking.", critical: false, kc: 0.6 },
    ],
    frostSensitiveStages: ["Emergence", "Squaring", "Flowering (Bloom)", "Boll Development", "Boll Opening"],
    frostThreshold: 2,
    heatSensitiveStages: ["Flowering (Bloom)"],
    heatThreshold: 38,
    pests: ["Bollworm / budworm complex", "Whitefly", "Pink bollworm", "Aphids", "Spider mites"],
    diseases: ["Verticillium wilt", "Bacterial blight", "Fusarium wilt", "Cotton leaf curl virus"],
    tips: [
      "Cotton has almost no frost tolerance at any stage.",
      "Short dry spells at flowering cause square and boll shedding — avoid stress here above all.",
      "Whitefly pressure in South Asia is tied to leaf curl virus; scout from squaring on.",
    ],
    caveat: "Assumes a typical full-season upland cotton cycle; stage length varies by variety and region.",
  },
  {
    key: "sunflower",
    label: "Sunflower",
    icon: "🌻",
    family: "Oilseed",
    seasonDays: 125,
    gddTotal: 1500,
    gddBase: 8,
    gddCap: 30,
    taw: 140,
    depletionTrigger: 0.55,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings emerge.", critical: false, kc: 0.35 },
      { name: "Vegetative Growth", startFrac: 0.09, desc: "Leaves develop and the bud forms.", critical: false, kc: 0.7 },
      { name: "Flowering", startFrac: 0.44, desc: "The head opens and pollinates — the critical yield window.", critical: true, kc: 1.1 },
      { name: "Seed Filling", startFrac: 0.6, desc: "Seeds and oil fill out.", critical: true, kc: 1.0 },
      { name: "Maturity", startFrac: 0.82, desc: "The back of the head yellows and dries.", critical: false, kc: 0.4 },
    ],
    frostSensitiveStages: ["Flowering", "Seed Filling"],
    frostThreshold: 0,
    heatSensitiveStages: ["Flowering"],
    heatThreshold: 35,
    pests: ["Sunflower moth", "Cutworm", "Birds at maturity"],
    diseases: ["Sclerotinia head/stalk rot", "Downy mildew", "Rust", "Phomopsis"],
    tips: [
      "Deep roots let sunflower ride out mid-season dryness — don't over-irrigate early.",
      "Sclerotinia risk is high in wet weather at flowering; rotation is the main control.",
      "Water stress at flowering hits oil content as well as yield.",
    ],
    caveat: "Oilseed sunflower timings; confectionery types can run longer.",
  },
  {
    key: "canola",
    label: "Canola / Rapeseed",
    icon: "🌼",
    family: "Oilseed",
    seasonDays: 135,
    gddTotal: 1600,
    gddBase: 5,
    gddCap: 27,
    taw: 100,
    depletionTrigger: 0.5,
    stages: [
      { name: "Emergence", startFrac: 0, desc: "Seedlings emerge — the most vulnerable stage of the whole season.", critical: false, kc: 0.35 },
      { name: "Rosette", startFrac: 0.09, desc: "A low rosette of leaves builds before stems rise.", critical: false, kc: 0.6 },
      { name: "Bolting", startFrac: 0.3, desc: "Stems elongate and buds form.", critical: false, kc: 0.9 },
      { name: "Flowering", startFrac: 0.45, desc: "Yellow bloom — the critical window for yield and for disease.", critical: true, kc: 1.1 },
      { name: "Pod Filling", startFrac: 0.63, desc: "Pods and seeds fill.", critical: true, kc: 0.95 },
      { name: "Maturity", startFrac: 0.85, desc: "Pods ripen and the crop is swathed or desiccated.", critical: false, kc: 0.4 },
    ],
    frostSensitiveStages: ["Flowering", "Pod Filling"],
    frostThreshold: -1,
    heatSensitiveStages: ["Flowering"],
    heatThreshold: 30,
    pests: ["Flea beetle at emergence", "Pollen beetle", "Cabbage stem flea beetle", "Aphids"],
    diseases: ["Sclerotinia stem rot", "Blackleg", "Light leaf spot", "Clubroot"],
    tips: [
      "Flea beetle at the cotyledon stage can wipe out a stand in days — check the first two weeks daily.",
      "Sclerotinia spray decisions are made at early-to-mid flower, based on wet weather.",
      "Heat above 30°C during flowering causes flower blast and missing pods.",
    ],
    caveat: "Spring canola cycle. Winter oilseed rape is autumn-sown with a dormant period and is not modelled here.",
  },
  {
    key: "potato",
    label: "Potato",
    icon: "🥔",
    family: "Root & Tuber",
    seasonDays: 120,
    gddTotal: 1300,
    gddBase: 7,
    gddCap: 30,
    taw: 80,
    depletionTrigger: 0.35,
    stages: [
      { name: "Sprouting & Emergence", startFrac: 0, desc: "Shoots break the surface from the seed tuber.", critical: false, kc: 0.4 },
      { name: "Vegetative Growth", startFrac: 0.17, desc: "Canopy builds and covers the rows.", critical: false, kc: 0.8 },
      { name: "Tuber Initiation", startFrac: 0.33, desc: "Tubers are set — the number you get is decided here.", critical: true, kc: 1.1 },
      { name: "Tuber Bulking", startFrac: 0.46, desc: "Tubers fill. Steady moisture matters more than total rainfall.", critical: true, kc: 1.15 },
      { name: "Maturity & Skin Set", startFrac: 0.83, desc: "Haulm dies back and skins set for storage.", critical: false, kc: 0.75 },
    ],
    frostSensitiveStages: ["Sprouting & Emergence", "Vegetative Growth", "Tuber Initiation", "Tuber Bulking"],
    frostThreshold: 0,
    heatSensitiveStages: ["Tuber Initiation", "Tuber Bulking"],
    heatThreshold: 30,
    pests: ["Colorado potato beetle", "Aphids (virus vectors)", "Wireworm", "Potato tuber moth"],
    diseases: ["Late blight (Phytophthora)", "Early blight", "Blackleg", "Common scab"],
    tips: [
      "Potato has shallow roots and a small water buffer — it needs little and often, not one big soak.",
      "Swings between dry and wet during bulking cause growth cracks and hollow heart.",
      "Late blight moves in warm humid weather; forecast rain during bulking is your spray trigger.",
    ],
    caveat: "Timings suit a main-crop potato. Early/new potato varieties run considerably shorter.",
  },
  {
    key: "tomato",
    label: "Tomato (Field)",
    icon: "🍅",
    family: "Vegetable",
    seasonDays: 135,
    gddTotal: 1500,
    gddBase: 10,
    gddCap: 32,
    taw: 90,
    depletionTrigger: 0.4,
    stages: [
      { name: "Establishment", startFrac: 0, desc: "Transplants root in or seedlings emerge.", critical: false, kc: 0.45 },
      { name: "Vegetative Growth", startFrac: 0.15, desc: "The plant builds frame and canopy.", critical: false, kc: 0.75 },
      { name: "Flowering & Fruit Set", startFrac: 0.35, desc: "Flowers set fruit — sensitive to heat and to uneven watering.", critical: true, kc: 1.15 },
      { name: "Fruit Development", startFrac: 0.55, desc: "Fruit sizes up. Consistency here prevents cracking and blossom end rot.", critical: true, kc: 1.15 },
      { name: "Ripening & Harvest", startFrac: 0.8, desc: "Fruit colours up and picking begins.", critical: false, kc: 0.8 },
    ],
    frostSensitiveStages: ["Establishment", "Vegetative Growth", "Flowering & Fruit Set", "Fruit Development", "Ripening & Harvest"],
    frostThreshold: 2,
    heatSensitiveStages: ["Flowering & Fruit Set"],
    heatThreshold: 34,
    pests: ["Tomato fruitworm / Helicoverpa", "Whitefly", "Leafminer", "Spider mites"],
    diseases: ["Late blight", "Early blight", "Bacterial spot", "Fusarium wilt", "TYLCV"],
    tips: [
      "Blossom end rot is a calcium-delivery problem caused by uneven watering, not a disease.",
      "Night temperatures above roughly 24°C at flowering block fruit set.",
      "Drip irrigation plus mulch beats overhead watering for disease control.",
    ],
    caveat: "Field tomato under normal management. Protected/greenhouse crops run on a different schedule entirely.",
  },
  {
    key: "sugarcane",
    label: "Sugarcane",
    icon: "🎋",
    family: "Sugar",
    seasonDays: 330,
    gddTotal: 4200,
    gddBase: 10,
    gddCap: 35,
    taw: 150,
    depletionTrigger: 0.6,
    stages: [
      { name: "Germination", startFrac: 0, desc: "Setts sprout and shoots appear.", critical: false, kc: 0.4 },
      { name: "Tillering", startFrac: 0.12, desc: "Shoots multiply and the stand fills in.", critical: false, kc: 0.8 },
      { name: "Grand Growth", startFrac: 0.3, desc: "Rapid stalk elongation — by far the biggest water demand of the cycle.", critical: true, kc: 1.25 },
      { name: "Maturation", startFrac: 0.75, desc: "Sugar accumulates in the stalk.", critical: false, kc: 0.9 },
      { name: "Ripening", startFrac: 0.9, desc: "Controlled drying raises sugar recovery before harvest.", critical: false, kc: 0.7 },
    ],
    frostSensitiveStages: ["Germination", "Tillering", "Grand Growth"],
    frostThreshold: 2,
    heatSensitiveStages: [],
    heatThreshold: 45,
    pests: ["Top borer", "Stem borer", "Pyrilla", "Termites"],
    diseases: ["Red rot", "Smut", "Wilt", "Ratoon stunting disease"],
    tips: [
      "Grand growth is where irrigation pays; stress here costs tonnage you cannot recover.",
      "Deliberately drying the crop in the last few weeks raises sugar recovery.",
      "Use disease-free seed cane — red rot and RSD spread mainly through planting material.",
    ],
    caveat: "Plant-cane cycles run roughly 10-12 months and ratoon crops differ. Regional practice varies a lot.",
  },
];

export const CROP_MAP: Record<string, Crop> = Object.fromEntries(CROPS.map((c) => [c.key, c]));

export const DEFAULT_CROP = CROPS[0]!;

export function getCrop(key: string | null | undefined): Crop {
  return (key ? CROP_MAP[key] : undefined) ?? DEFAULT_CROP;
}
